version: '2'
services:
    knowmyminister-app:
        image: knowmyminister
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://knowmyminister-mysql:3306/knowmyminister?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=knowmyminister-elasticsearch:9300
        ports:
            - 8080:8080
    knowmyminister-mysql:
        extends:
            file: mysql.yml
            service: knowmyminister-mysql
    knowmyminister-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: knowmyminister-elasticsearch
